=begin comment

Prototype

Seed for discussion: can be implemented for asserting a repository is FAIR. Directories that contain lists of scored FAIR repositories can call this API on repos that implement it in order to automate some of the scoring process.

OpenAPI spec version: 0.0.2
Contact: krobasky@renci.org
Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::SwaggerClient::DefaultApi');

my $api = WWW::SwaggerClient::DefaultApi->new();
isa_ok($api, 'WWW::SwaggerClient::DefaultApi');

#
# objects_get test
#
{
    my $keyword = undef; # replace NULL with a proper value
    my $page_size = undef; # replace NULL with a proper value
    my $page_number = undef; # replace NULL with a proper value
    my $result = $api->objects_get(keyword => $keyword, page_size => $page_size, page_number => $page_number);
}

#
# objects_objectid_get test
#
{
    my $objectid = undef; # replace NULL with a proper value
    my $result = $api->objects_objectid_get(objectid => $objectid);
}

#
# repo_info_get test
#
{
    my $scoring_engine = undef; # replace NULL with a proper value
    my $result = $api->repo_info_get(scoring_engine => $scoring_engine);
}


1;
